version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    # TODO: Allow `eslint` to update to version 10 after `eslint-plugin-github` updates with support for v10 too
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
